services:
  samba-ad:
    build: .
    user: "0:0"
    privileged: true
    container_name: samba-ad
    hostname: ${SAMBA_HOSTNAME}
    domainname: ${SAMBA_DOMAINNAME}
    restart: unless-stopped
    environment:
      TZ: ${SAMBA_TIMEZONE}
      DOMAIN: ${SAMBA_DOMAIN}
      REALM: ${SAMBA_REALM}
      ADMIN_PASSWORD: ${SAMBA_ADMIN_PASSWORD}
      DNS_FORWARDER: ${SAMBA_DNS_FORWARDER}
      HOST_IP: ${SAMBA_IPV4_ADDRESS}
      SERVER_ROLE: domain controller
    volumes:
      - ./samba/config:/etc/samba
      - ./samba/data:/var/lib/samba
      - samba_cache:/var/cache/samba
      - samba_logs:/var/log/samba
      - samba_sysvol:/var/lib/samba/sysvol
      - samba_netlogon:/var/lib/samba/netlogon
    ports:
      - "${SAMBA_IPV4_ADDRESS}:53:53/tcp"
      - "${SAMBA_IPV4_ADDRESS}:53:53/udp"
      - "${SAMBA_IPV4_ADDRESS}:88:88/tcp"
      - "${SAMBA_IPV4_ADDRESS}:88:88/udp"
      - "${SAMBA_IPV4_ADDRESS}:135:135/tcp"
      - "${SAMBA_IPV4_ADDRESS}:137:137/udp"
      - "${SAMBA_IPV4_ADDRESS}:138:138/udp"
      - "${SAMBA_IPV4_ADDRESS}:139:139/tcp"
      - "${SAMBA_IPV4_ADDRESS}:389:389/tcp"
      - "${SAMBA_IPV4_ADDRESS}:389:389/udp"
      - "${SAMBA_IPV4_ADDRESS}:445:445/tcp"
      - "${SAMBA_IPV4_ADDRESS}:464:464/tcp"
      - "${SAMBA_IPV4_ADDRESS}:464:464/udp"
      - "${SAMBA_IPV4_ADDRESS}:636:636/tcp"
      - "${SAMBA_IPV4_ADDRESS}:3268:3268/tcp"
      - "${SAMBA_IPV4_ADDRESS}:3269:3269/tcp"
    dns:
      - 127.0.0.1

volumes:
  samba_cache:
  samba_logs:
  samba_sysvol:
  samba_netlogon:

